CREATE TABLE IF NOT EXISTS `permissions` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `type` enum('all','page','menu','module','record') COLLATE cp1251_bulgarian_ci NOT NULL DEFAULT 'page',
  `object` varchar(20) COLLATE cp1251_bulgarian_ci NOT NULL,
  `yes_no` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  KEY `user_id` (`user_id`),
  KEY `type` (`type`),
  KEY `object` (`object`)
) ENGINE=InnoDB  DEFAULT CHARSET=cp1251 COLLATE=cp1251_bulgarian_ci AUTO_INCREMENT=1 ;
-- --------------------------------------------------------
INSERT INTO `content` (`name`,`nolink`,`date_time_1`,`date_time_2`,`language`,`text`) VALUES
('usermenu_addtomenu',1,NOW(),NOW(),'bg','Линк в менюто на текущата страница'),
('usermenu_addtomenu',1,NOW(),NOW(),'en','Add a link to the new page at the current page'),
('usermenu_back',1,NOW(),NOW(),'bg','Връщане обратно'),
('usermenu_back',1,NOW(),NOW(),'en','Go back'),
('usermenu_cantdelindex',1,NOW(),NOW(),'bg','Не можете да изтриете главната страница на раздел, докато в този раздел има други страници.'),
('usermenu_cantdelindex',1,NOW(),NOW(),'en','You can not delete the main page of a section, while this section has pages.'),
('usermenu_confirdeleting',1,NOW(),NOW(),'bg','Изтриването на страница ще направи невалидни всички хипервръзки, които сочат към нея. Наистина ли искате да изтриете тази страница?'),
('usermenu_confirdeleting',1,NOW(),NOW(),'en','Deleting a page will break all links to it. Do you really want to delete this page?'),
('usermenu_createnewpage',1,NOW(),NOW(),'bg','Създаване на нова страница'),
('usermenu_createnewpage',1,NOW(),NOW(),'en','Create a new page'),
('usermenu_editmenu',1,NOW(),NOW(),'en','Link editing'),
('usermenu_editmenu',1,NOW(),NOW(),'bg','Редактиране на линк от меню'),
('usermenu_edittext',1,NOW(),NOW(),'bg','Редактиране на текст'),
('usermenu_edittext',1,NOW(),NOW(),'en','Editing Text'),
('usermenu_language',1,NOW(),NOW(),'bg','Език:'),
('usermenu_language',1,NOW(),NOW(),'en','Language:'),
('usermenu_linktext',1,NOW(),NOW(),'bg','Текст на линка в менюто:'),
('usermenu_linktext',1,NOW(),NOW(),'en','Text on the link to page:'),
('usermenu_menugroup',1,NOW(),NOW(),'en','Menu id:'),
('usermenu_menugroup',1,NOW(),NOW(),'bg','Номер на менюто:'),
('usermenu_menulinkdb',1,NOW(),NOW(),'en','ID of the page linked:'),
('usermenu_menulinkdb',1,NOW(),NOW(),'bg','Номер на страница или относителен адрес<br>\r\nстраница, която се отваря от линка:'),
('usermenu_menupos',1,NOW(),NOW(),'bg','Позиция в менюто:'),
('usermenu_menupos',1,NOW(),NOW(),'en','Position in the menu:'),
('usermenu_menutext',1,NOW(),NOW(),'en','Text on the link:'),
('usermenu_menutext',1,NOW(),NOW(),'bg','Текст варху линка:'),
('usermenu_newmenu',1,NOW(),NOW(),'bg','Нов раздел:'),
('usermenu_newmenu',1,NOW(),NOW(),'en','New section:'),
('usermenu_newpagecontent',1,NOW(),NOW(),'bg','Съдържание на страницата:'),
('usermenu_newpagecontent',1,NOW(),NOW(),'en','Page Content:'),
('usermenu_newpagesubmit',1,NOW(),NOW(),'bg','Създаване и отваряне на страницата'),
('usermenu_newpagesubmit',1,NOW(),NOW(),'en','Create and open the page'),
('usermenu_newpagetitle',1,NOW(),NOW(),'bg','Заглавие:'),
('usermenu_newpagetitle',1,NOW(),NOW(),'en','Heading:'),
('usermenu_texttoedit',1,NOW(),NOW(),'bg','Text:'),
('usermenu_texttoedit',1,NOW(),NOW(),'en','Text:');