CREATE TABLE IF NOT EXISTS `feedback` (
  `ID` int(11) NOT NULL,
  `page_id` int(11) NOT NULL,
  `date_time_1` datetime NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `subject` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `publish` tinyint(1) NOT NULL,
  `text` text COLLATE utf8_unicode_ci NOT NULL,
  `referer` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `IP` varchar(15) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
-- --------------------------------------------------------
INSERT INTO `content` (`name`,`nolink`,`date_time_1`,`date_time_2`,`language`,`text`) VALUES
('feedback_publish',1,NOW(),NOW(),'bg','Публикуване:'),
('feedback_publish',0,NOW(),NOW(),'en','Publish:'),
('feedback_publish2',0,NOW(),NOW(),'bg','Съгласни ли сте Вашето мнение да бъде публикувано на сайта?'),
('feedback_publish2',0,NOW(),NOW(),'en','Do you want your opinion to be displayed on this site?'),
('feedback_recaptcha',0,NOW(),NOW(),'bg','Поставете отметка:'),
('feedback_recaptcha',0,NOW(),NOW(),'en',''),
('feedback_subject',1,NOW(),NOW(),'bg','Относно:'),
('feedback_subject',0,NOW(),NOW(),'en','Subject:'),
('feedback_subject_1061',1,NOW(),NOW(),'bg','Конференция ВСУ`2014'),
('feedback_subject_1061',1,NOW(),NOW(),'en','VSU`2014 conference'),
('feedback_subject_383',1,NOW(),NOW(),'bg','Прием 2017 - Висше строително училище Любен Каравелов'),
('feedback_subject_383',1,NOW(),NOW(),'en','Admission 2017'),
('feedback_submit',1,NOW(),NOW(),'bg','Изпращане'),
('feedback_submit',1,NOW(),NOW(),'en','Send'),
('feedback_text',1,NOW(),NOW(),'bg','Текст:'),
('feedback_text',0,NOW(),NOW(),'en','Text:'),
('feedback_thanks',1,NOW(),NOW(),'bg','<p class="message">Благодарим Ви, за изпратената информация!</p>'),
('feedback_thanks',1,NOW(),NOW(),'en','<p class="message">Thank you for sharing our opinions.</p>'),
('feedback_tologin',0,NOW(),NOW(),'bg','Ако сте се регистрирали на този сайт, за да избегнете повторно попълването на някои полета, влезте с потребителското си име и парола през страница '),
('feedback_tologin',0,NOW(),NOW(),'en','If you have registered on this site to avoid repeated filling in of some fields, log in with your username and password through the page '),
('feedback_to_1061',1,NOW(),NOW(),'en','conference_en@vsu.bg'),
('feedback_to_1061',1,NOW(),NOW(),'bg','conference_bg@vsu.bg'),
('feedback_to_366',1,NOW(),NOW(),'en','conference_en@vsu.bg'),
('feedback_to_366',1,NOW(),NOW(),'bg','conference_bg@vsu.bg'),
('feedback_to_383',1,NOW(),NOW(),'bg','priem@vsu.bg'),
('feedback_to_383',1,NOW(),NOW(),'en','vanyog@gmail.com'),
('feedback_youremail',1,NOW(),NOW(),'bg','Вашият имейл:'),
('feedback_youremail',0,NOW(),NOW(),'en','E-mail:'),
('feedback_yourname',1,NOW(),NOW(),'bg','Вашето име:'),
('feedback_yourname',0,NOW(),NOW(),'en','Your name:');