CREATE TABLE IF NOT EXISTS `users` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `date_time_0` datetime NOT NULL,
  `date_time_1` datetime NOT NULL,
  `date_time_2` datetime NOT NULL,
  `username` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `password` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `email` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `firstname` varchar(100) CHARACTER SET utf8 NOT NULL,
  `secondname` varchar(100) CHARACTER SET utf32 NOT NULL,
  `thirdname` varchar(100) CHARACTER SET utf32 NOT NULL,
  `telephone` varchar(20) NOT NULL,
  `IP` varchar(15) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `username` (`username`),
  KEY `password` (`password`),
  KEY `date_time_0` (`date_time_0`),
  KEY `date_time_1` (`date_time_1`),
  KEY `date_time_3` (`date_time_2`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
-- --------------------------------------------------------
INSERT INTO `content` (`name`,`nolink`,`date_time_1`,`date_time_2`,`language`,`text`) VALUES
('user_delete',1,NOW(),NOW(),'bg','Изтриване на потребителя'),
('user_email',1,NOW(),NOW(),'bg','Имейл:'),
('user_email',1,NOW(),NOW(),'bg','Имейл:'),
('user_enter',1,NOW(),NOW(),'bg','Вход'),
('user_enter',1,NOW(),NOW(),'bg','Вход'),
('user_firstname',1,NOW(),NOW(),'bg','Име:'),
('user_firstname',1,NOW(),NOW(),'bg','Име:'),
('user_firstuser',1,NOW(),NOW(),'bg','<p>На сайта все още няма регистрирани потребители. Сега ше регистрирате първия потребител.</p>'),
('user_firstuser',1,NOW(),NOW(),'bg','<p>На сайта все още няма регистрирани потребители. Сега ше регистрирате първия потребител.</p>'),
('user_logaut',1,NOW(),NOW(),'bg','Изход'),
('user_logaut',1,NOW(),NOW(),'bg','Изход'),
('user_login',1,NOW(),NOW(),'bg','Влизане в системата'),
('user_login',1,NOW(),NOW(),'bg','Влизане в системата'),
('user_login_button',1,NOW(),NOW(),'bg','Влизане'),
('user_login_button',1,NOW(),NOW(),'en','Log in'),
('user_login_button',1,NOW(),NOW(),'bg','Влизане'),
('user_login_button',1,NOW(),NOW(),'en','Log in'),
('user_logoutcontent',1,NOW(),NOW(),'bg','<p>Вие успешно излязохте от системата</p>'),
('user_logoutcontent',1,NOW(),NOW(),'bg','<p>Вие успешно излязохте от системата</p>'),
('user_logouttitle',1,NOW(),NOW(),'bg','Изход от системата'),
('user_logouttitle',1,NOW(),NOW(),'bg','Изход от системата'),
('user_newreg',1,NOW(),NOW(),'bg','Нова регистрация'),
('user_newreg',1,NOW(),NOW(),'bg','Нова регистрация'),
('user_password',1,NOW(),NOW(),'bg','Парола:'),
('user_password',1,NOW(),NOW(),'bg','Парола:'),
('user_passwordchanged',1,NOW(),NOW(),'bg','Паролата беше сменена. При следващото влизане използвайте новата парола.'),
('user_passwordchanged',1,NOW(),NOW(),'bg','Паролата беше сменена. При следващото влизане използвайте новата парола.'),
('user_passwordconfirm',1,NOW(),NOW(),'bg','Повторение на паролата:'),
('user_passwordconfirm',1,NOW(),NOW(),'bg','Повторение на паролата:'),
('user_passwordinvalid',1,NOW(),NOW(),'bg','Паролата и нейното повторение не съвпадаха. Паролата не е променена.'),
('user_passwordinvalid',1,NOW(),NOW(),'bg','Паролата и нейното повторение не съвпадаха. Паролата не е променена.'),
('user_savenew',1,NOW(),NOW(),'bg','Запазване на данните'),
('user_secondname',1,NOW(),NOW(),'bg','Презиме:'),
('user_secondname',1,NOW(),NOW(),'bg','Презиме:'),
('user_telephone',1,NOW(),NOW(),'bg','Телефон:'),
('user_telephone',1,NOW(),NOW(),'bg','Телефон:'),
('user_thirdname',1,NOW(),NOW(),'bg','Фамилия:'),
('user_thirdname',1,NOW(),NOW(),'bg','Фамилия:'),
('user_username',1,NOW(),NOW(),'bg','Потребителско име:'),
('user_username',1,NOW(),NOW(),'bg','Потребителско име:');