CREATE TABLE IF NOT EXISTS `users` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `type` varchar(50) NOT NULL,
  `date_time_0` datetime NOT NULL,
  `date_time_1` datetime NOT NULL,
  `date_time_2` datetime NOT NULL,
  `username` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `password` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `newpass` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `email` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `code` varchar(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `firstname` varchar(100) CHARACTER SET utf8 NOT NULL,
  `secondname` varchar(100) CHARACTER SET utf8 NOT NULL,
  `thirdname` varchar(100) CHARACTER SET utf8 NOT NULL,
  `country` varchar(2) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `institution` varchar(255) CHARACTER SET utf8 NOT NULL,
  `address` text CHARACTER SET utf8 NOT NULL,
  `telephone` varchar(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `IP` varchar(15) CHARACTER SET armscii8 COLLATE armscii8_bin NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `username` (`username`),
  KEY `password` (`password`),
  KEY `date_time_0` (`date_time_0`),
  KEY `date_time_1` (`date_time_1`),
  KEY `date_time_3` (`date_time_2`),
  KEY `code` (`code`),
  KEY `type` (`type`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
-- --------------------------------------------------------
INSERT INTO `content` (`name`,`nolink`,`date_time_1`,`date_time_2`,`language`,`text`) VALUES
('user_address',1,NOW(),NOW(),'bg','Адрес:'),
('user_address',1,NOW(),NOW(),'en','Address:'),
('user_backto',1,NOW(),NOW(),'bg','Връщане към:'),
('user_backto',1,NOW(),NOW(),'en','Go to:'),
('user_country',1,NOW(),NOW(),'bg','Държава:'),
('user_country',1,NOW(),NOW(),'en','Country:'),
('user_delete',1,NOW(),NOW(),'bg','Изтриване на потребителя'),
('user_email',1,NOW(),NOW(),'bg','Имейл:'),
('user_email',1,NOW(),NOW(),'en','E-mail:'),
('user_enter',1,NOW(),NOW(),'bg','Вход'),
('user_enter',0,NOW(),NOW(),'en','Login'),
('user_firstname',1,NOW(),NOW(),'bg','Име:'),
('user_firstname',1,NOW(),NOW(),'en','Name:'),
('user_firstuser',1,NOW(),NOW(),'bg','<p>На сайта все още няма регистрирани потребители. Сега ше регистрирате първия потребител.</p>'),
('user_firstuser',0,NOW(),NOW(),'en','<p>Site has not yet registered users. Now we register the first user.</p>'),
('user_homеpage',1,NOW(),NOW(),'bg','Началната страница'),
('user_homеpage',1,NOW(),NOW(),'en','Home page'),
('user_institution',1,NOW(),NOW(),'bg','Месторабота:'),
('user_institution',1,NOW(),NOW(),'en','Institution:'),
('user_lastpage',1,NOW(),NOW(),'bg','Предишната страница'),
('user_lastpage',1,NOW(),NOW(),'en','Previous Page'),
('user_logaut',1,NOW(),NOW(),'bg','Изход'),
('user_logaut',1,NOW(),NOW(),'en','Logout'),
('user_login',1,NOW(),NOW(),'bg','Влизане в системата'),
('user_login',1,NOW(),NOW(),'en','User login'),
('user_login_button',1,NOW(),NOW(),'bg','Влизане'),
('user_login_button',1,NOW(),NOW(),'en','Log in'),
('user_logoutcontent',1,NOW(),NOW(),'bg','<p>Вие успешно излязохте от системата</p>'),
('user_logoutcontent',1,NOW(),NOW(),'en','<p>You have successfully logged out of the system</p>'),
('user_logouttitle',1,NOW(),NOW(),'bg','Изход от системата'),
('user_logouttitle',1,NOW(),NOW(),'en','Log out page'),
('user_newreg',1,NOW(),NOW(),'bg','Нова регистрация'),
('user_newreg',0,NOW(),NOW(),'en','New registration'),
('user_password',1,NOW(),NOW(),'bg','Парола:'),
('user_password',1,NOW(),NOW(),'en','Password:'),
('user_passwordchanged',1,NOW(),NOW(),'bg','Паролата беше сменена. При следващото влизане използвайте новата парола.'),
('user_passwordchanged',0,NOW(),NOW(),'en','The password was changed. The next time use the new password.'),
('user_passwordconfirm',1,NOW(),NOW(),'bg','Повторение на паролата:'),
('user_passwordconfirm',1,NOW(),NOW(),'en','Repeat password:'),
('user_passwordinvalid',1,NOW(),NOW(),'bg','Паролата и нейното повторение не съвпадаха. Паролата не е променена.'),
('user_passwordinvalid',0,NOW(),NOW(),'en','Password and its repetition does not match. Password is not changed.'),
('user_savenew',1,NOW(),NOW(),'bg','Създаване на нов потребител'),
('user_savenew',1,NOW(),NOW(),'en','Create a new user'),
('user_secondname',1,NOW(),NOW(),'bg','Презиме:'),
('user_secondname',1,NOW(),NOW(),'en','Surname:'),
('user_telephone',1,NOW(),NOW(),'bg','Телефон:'),
('user_telephone',1,NOW(),NOW(),'en','Phone:'),
('user_thirdname',1,NOW(),NOW(),'bg','Фамилия:'),
('user_thirdname',1,NOW(),NOW(),'en','Family:'),
('user_username',1,NOW(),NOW(),'bg','Потребителско име:'),
('user_username',1,NOW(),NOW(),'en','Username:');
