INSERT INTO `content` (`name`,`nolink`,`date_time_1`,`date_time_2`,`language`,`text`) VALUES
('conference_1paper',1,NOW(),NOW(),'en','First report:'),
('conference_1paper',1,NOW(),NOW(),'bg','Първи доклад:'),
('conference_2paper',1,NOW(),NOW(),'en','Second report:'),
('conference_2paper',1,NOW(),NOW(),'bg','Втори доклад:'),
('conference_by',1,NOW(),NOW(),'bg','Заявен от:'),
('conference_by',1,NOW(),NOW(),'en','Sent by:'),
('conference_bycat',1,NOW(),NOW(),'bg','Брой резюмета по тематични направления'),
('conference_bycat',1,NOW(),NOW(),'en','Number of abstracts by topic'),
('conference_bycountry',1,NOW(),NOW(),'bg','По държави'),
('conference_bycountry',1,NOW(),NOW(),'en','By countries'),
('conference_byform',1,NOW(),NOW(),'bg','По форма на представяне'),
('conference_byform',1,NOW(),NOW(),'en','By registration form'),
('conference_cabstract',1,NOW(),NOW(),'en','Abstract:'),
('conference_cabstract',1,NOW(),NOW(),'bg','Резюме:'),
('conference_caddresses',1,NOW(),NOW(),'en','Addresses of authors:'),
('conference_caddresses',1,NOW(),NOW(),'bg','Адрес/адреси на авторите:'),
('conference_cauthors',1,NOW(),NOW(),'en','Authors:'),
('conference_cauthors',1,NOW(),NOW(),'bg','Автори:'),
('conference_cdate1',1,NOW(),NOW(),'en','First registered:'),
('conference_cdate1',1,NOW(),NOW(),'bg','Първо регистриране:'),
('conference_cdate2',1,NOW(),NOW(),'en','Last edited:'),
('conference_cdate2',1,NOW(),NOW(),'bg','Последна редакция:'),
('conference_cemail',1,NOW(),NOW(),'bg','Моля проверете си имейла и отворете адреса, който Ви беше изпратен.'),
('conference_cemail',1,NOW(),NOW(),'en','Please check your email and open the web address that was sent.'),
('conference_cfile',1,NOW(),NOW(),'en','File with the full text:'),
('conference_cfile',1,NOW(),NOW(),'bg','Файл с пълния текст:'),
('conference_cform',1,NOW(),NOW(),'bg','Форма на представяне:'),
('conference_cform',1,NOW(),NOW(),'en','Form of presentation:'),
('conference_cfulltextfile',1,NOW(),NOW(),'en','DOC file with the full text:'),
('conference_cfulltextfile',1,NOW(),NOW(),'bg','DOC файл с пълния текст:'),
('conference_cfulltextfile2',1,NOW(),NOW(),'en','PDF file with the full text:'),
('conference_cfulltextfile2',1,NOW(),NOW(),'bg','PDF файл с пълния текст:'),
('conference_cfulltextfile3',0,NOW(),NOW(),'bg','Презентация за пленарен доклад'),
('conference_cfulltextfile3',0,NOW(),NOW(),'en','Presentation file'),
('conference_ckeywords',1,NOW(),NOW(),'en','Keywords:'),
('conference_ckeywords',1,NOW(),NOW(),'bg','Ключови думи:'),
('conference_cnnotedit',1,NOW(),NOW(),'bg','Вие не може да редактирате този доклад.'),
('conference_cnnotedit',1,NOW(),NOW(),'en','You have no permission to edit this data.'),
('conference_csubmit',1,NOW(),NOW(),'en','Save data'),
('conference_csubmit',1,NOW(),NOW(),'bg','Запазване на данните'),
('conference_ctitle',1,NOW(),NOW(),'en','Title:'),
('conference_ctitle',1,NOW(),NOW(),'bg','Заглавие:'),
('conference_ctopic',1,NOW(),NOW(),'en','Conference topic:'),
('conference_ctopic',1,NOW(),NOW(),'bg','Тематично направление:'),
('conference_dfull',0,NOW(),NOW(),'en','Full Text Download'),
('conference_dfull',0,NOW(),NOW(),'bg','Пълен текст'),
('conference_editpaper',1,NOW(),NOW(),'en','Edit data'),
('conference_editpaper',1,NOW(),NOW(),'bg','Редактиране'),
('conference_emcofirmed',1,NOW(),NOW(),'bg','Вашият имейл адрес е потвърден. За всизане в сайта използвайте като потребителско име своя имейл адрес и паролата, която зададохте при регистрацията.'),
('conference_emcofirmed',1,NOW(),NOW(),'en','Your email address is confirmed. To log in the site, use your email address as username and the password you set during the registration.'),
('conference_fee',1,NOW(),NOW(),'bg','Платена такса<sup>1</sup>:'),
('conference_fee',1,NOW(),NOW(),'en','Fee paid<sup>1</sup>:'),
('conference_feenote',1,NOW(),NOW(),'bg','<p><sup>1</sup> Сумата на платената такса ще се покаже тук след потвърждение от Финансово-счетоводен отдел.</p>'),
('conference_feenote',1,NOW(),NOW(),'en','<p><sup>1</sup> The amount of the fee will appear here after confirmation of Financial Department.</p>'),
('conference_fileagain',1,NOW(),NOW(),'bg','На сървъра вече има файл със същото име, качен от друг участник. Моля, преименувайте своя файл и отново опитайте да го качите.'),
('conference_fileagain',1,NOW(),NOW(),'en','There is a file with the same name on the server, may be posted by another participant. Please rename your file and then try to upload it again.'),
('conference_filenotexists',1,NOW(),NOW(),'bg','Файлът не съществува! Моля, качете го отново.'),
('conference_filenotexists',1,NOW(),NOW(),'en','File do not exist! Please, try to upload again.'),
('conference_forms',1,NOW(),NOW(),'bg','$fs = array( \'Презентация\', \'Постер\', \'Фирмен доклад\', \'Задочно участие\', \'Слушател\');\r\n'),
('conference_forms',1,NOW(),NOW(),'en','$fs = array( \'Oral presentation\', \'Poster\', \'Corporative presentation\', \'Part time\', \'Listener\' );'),
('conference_invalidcode',1,NOW(),NOW(),'bg','Невалиден код за потвърждаване на регистрация.'),
('conference_invalidcode',1,NOW(),NOW(),'en','Invalid confirmation code.'),
('conference_mydata',1,NOW(),NOW(),'bg','Данни в моя профил:'),
('conference_mydata',1,NOW(),NOW(),'en','My personal data:'),
('conference_mypaper',1,NOW(),NOW(),'en','My participation'),
('conference_mypaper',1,NOW(),NOW(),'bg','Моето участие в конференцията'),
('conference_mypersonal',1,NOW(),NOW(),'bg','Редактиране на профила'),
('conference_mypersonal',1,NOW(),NOW(),'en','Edit my personal data'),
('conference_noabs',1,NOW(),NOW(),'bg','Срокът за изпращане на резюмета е изтекъл. Сега може да качите само файлове с пълния текст на доклади.'),
('conference_noabs',1,NOW(),NOW(),'en','The deadline for abstracts has passed. Now you can upload only files with the full report.'),
('conference_noabs1',1,NOW(),NOW(),'bg','Няма данни за доклади'),
('conference_noabs1',1,NOW(),NOW(),'en','You have no reports yet.'),
('conference_nofull',1,NOW(),NOW(),'bg','Срокът за регистриране на доклади е изтекъл.'),
('conference_nofull',1,NOW(),NOW(),'en','The deadline for registration of reports is expired. '),
('conference_notspec',1,NOW(),NOW(),'bg','Не са посочили'),
('conference_notspec',1,NOW(),NOW(),'en','Not specified'),
('conference_noupload',1,NOW(),NOW(),'bg','За съжаление, файлът не се качи успешно. Моля, изпратете го на имейл <a href="mailto:conference_bg@vsu.bg">conference_bg@vsu.bg</a>.'),
('conference_noupload',1,NOW(),NOW(),'en','Unfortunately, the file is not uploaded successfully. Please send it to email <a href="mailto:conference_bg@vsu.bg">conference_en@vsu.bg</a>.'),
('conference_partcount',1,NOW(),NOW(),'bg','Брой онлайн регистрации'),
('conference_partcount',1,NOW(),NOW(),'en','Number of online registrations'),
('conference_pg',0,NOW(),NOW(),'bg','стр. '),
('conference_pg',0,NOW(),NOW(),'en','p. '),
('conference_posters',0,NOW(),NOW(),'bg','Постери'),
('conference_posters',0,NOW(),NOW(),'en','Posters'),
('conference_pregsubmit',1,NOW(),NOW(),'en','Registration'),
('conference_pregsubmit',1,NOW(),NOW(),'bg','Регистриране'),
('conference_prez',0,NOW(),NOW(),'bg','Презентация'),
('conference_prez',0,NOW(),NOW(),'en','Presentation Download'),
('conference_proccount',1,NOW(),NOW(),'bg','Брой изпратени резюмета'),
('conference_proccount',1,NOW(),NOW(),'en','Number of abstracts sent'),
('conference_recaptcha',1,NOW(),NOW(),'bg','Код за сигурност<br>\r\nReCaptcha'),
('conference_recaptcha',1,NOW(),NOW(),'en','Security Code:<br>\r\n(ReCaptcha)'),
('conference_regcmess',1,NOW(),NOW(),'bg','Здравейте,\r\n\r\nВашият имейл адрес е използван за регистриране на потребител или смяна на паролата на регистриран потребител на сайта http://www.vsu.bg\r\n\r\nАко това не сте направили Вие, моля, не правете нищо,\r\n\r\nно ако наистина искате да потвърдите регистрацията (смяната на паролата) си, отворете в браузъра си следния адрес:\r\n\r\n'),
('conference_regcmess',1,NOW(),NOW(),'en','Hello,\r\n\r\nYour email address is used to register a new user or to change the password of a registered user of the site http://www.vsu.bg\r\n\r\nIf you did not make this, please do not do anything,\r\n\r\nbut if you really want to confirm your registration (password change), open in your browser this URL:\r\n\r\n'),
('conference_title',1,NOW(),NOW(),'bg','Международна научна конференция VSU\''),
('conference_title',1,NOW(),NOW(),'en','International Scientific Conference VSU\''),
('conference_topics',1,NOW(),NOW(),'en','$tp = array(\r\n\'   I. Architecture and Urbanism\',\r\n\'  II. Art and Conservation of Architectural Heritage\',\r\n\' III. Structural Mechanics\',\r\n\'  IV. Building Structures\',\r\n\'   V. Building Physics and Materials Science\',\r\n\'  VI. Technology, Management and Economics of Construction\',\r\n\' VII. Sustainable Development and Environmental Security\',\r\n\'VIII. Student Section\',\r\n\'IX. College student Section\'\r\n);'),
('conference_topics',1,NOW(),NOW(),'bg','$tp = array(\r\n\'   I. Архитектура и урбанизъм\',\r\n\'  II. Изкуство и опазване на архитектурното наследство\',\r\n\' III. Строителна механика\',\r\n\'  IV. Строителни конструкции\',\r\n\'   V. Строителна физика и материалознание\',\r\n\'  VI. Технология и управление на строителството\',\r\n\' VII. Устойчиво строителство и екологична сигурност\',\r\n\'VIII. Студентска секция\',\r\n\' IХ. Ученическа секция\'\r\n);');-- --------------------------------------------------------
INSERT INTO `content` (`name`,`nolink`,`date_time_1`,`date_time_2`,`language`,`text`) VALUES
('conference_1paper',1,NOW(),NOW(),'en','First report:'),
('conference_1paper',1,NOW(),NOW(),'bg','РџСЉСЂРІРё РґРѕРєР»Р°Рґ:'),
('conference_2paper',1,NOW(),NOW(),'en','Second report:'),
('conference_2paper',1,NOW(),NOW(),'bg','Р’С‚РѕСЂРё РґРѕРєР»Р°Рґ:'),
('conference_by',1,NOW(),NOW(),'bg','Р—Р°СЏРІРµРЅ РѕС‚:'),
('conference_by',1,NOW(),NOW(),'en','Sent by:'),
('conference_bycat',1,NOW(),NOW(),'bg','Р‘СЂРѕР№ СЂРµР·СЋРјРµС‚Р° РїРѕ С‚РµРјР°С‚РёС‡РЅРё РЅР°РїСЂР°РІР»РµРЅРёСЏ'),
('conference_bycat',1,NOW(),NOW(),'en','Number of abstracts by topic'),
('conference_bycountry',1,NOW(),NOW(),'bg','РџРѕ РґСЉСЂР¶Р°РІРё'),
('conference_bycountry',1,NOW(),NOW(),'en','By countries'),
('conference_byform',1,NOW(),NOW(),'bg','РџРѕ С„РѕСЂРјР° РЅР° РїСЂРµРґСЃС‚Р°РІСЏРЅРµ'),
('conference_byform',1,NOW(),NOW(),'en','By registration form'),
('conference_cabstract',1,NOW(),NOW(),'en','Abstract:'),
('conference_cabstract',1,NOW(),NOW(),'bg','Р РµР·СЋРјРµ:'),
('conference_caddresses',1,NOW(),NOW(),'en','Addresses of authors:'),
('conference_caddresses',1,NOW(),NOW(),'bg','РђРґСЂРµСЃ/Р°РґСЂРµСЃРё РЅР° Р°РІС‚РѕСЂРёС‚Рµ:'),
('conference_cauthors',1,NOW(),NOW(),'en','Authors:'),
('conference_cauthors',1,NOW(),NOW(),'bg','РђРІС‚РѕСЂРё:'),
('conference_cdate1',1,NOW(),NOW(),'en','First registered:'),
('conference_cdate1',1,NOW(),NOW(),'bg','РџСЉСЂРІРѕ СЂРµРіРёСЃС‚СЂРёСЂР°РЅРµ:'),
('conference_cdate2',1,NOW(),NOW(),'en','Last edited:'),
('conference_cdate2',1,NOW(),NOW(),'bg','РџРѕСЃР»РµРґРЅР° СЂРµРґР°РєС†РёСЏ:'),
('conference_cemail',1,NOW(),NOW(),'bg','РњРѕР»СЏ РїСЂРѕРІРµСЂРµС‚Рµ СЃРё РёРјРµР№Р»Р° Рё РѕС‚РІРѕСЂРµС‚Рµ Р°РґСЂРµСЃР°, РєРѕР№С‚Рѕ Р’Рё Р±РµС€Рµ РёР·РїСЂР°С‚РµРЅ.'),
('conference_cemail',1,NOW(),NOW(),'en','Please check your email and open the web address that was sent.'),
('conference_cfile',1,NOW(),NOW(),'en','File with the full text:'),
('conference_cfile',1,NOW(),NOW(),'bg','Р¤Р°Р№Р» СЃ РїСЉР»РЅРёСЏ С‚РµРєСЃС‚:'),
('conference_cform',1,NOW(),NOW(),'bg','Р¤РѕСЂРјР° РЅР° РїСЂРµРґСЃС‚Р°РІСЏРЅРµ:'),
('conference_cform',1,NOW(),NOW(),'en','Form of presentation:'),
('conference_cfulltextfile',1,NOW(),NOW(),'en','DOC file with the full text:'),
('conference_cfulltextfile',1,NOW(),NOW(),'bg','DOC С„Р°Р№Р» СЃ РїСЉР»РЅРёСЏ С‚РµРєСЃС‚:'),
('conference_cfulltextfile2',1,NOW(),NOW(),'en','PDF file with the full text:'),
('conference_cfulltextfile2',1,NOW(),NOW(),'bg','PDF С„Р°Р№Р» СЃ РїСЉР»РЅРёСЏ С‚РµРєСЃС‚:'),
('conference_cfulltextfile3',0,NOW(),NOW(),'bg','РџСЂРµР·РµРЅС‚Р°С†РёСЏ Р·Р° РїР»РµРЅР°СЂРµРЅ РґРѕРєР»Р°Рґ'),
('conference_cfulltextfile3',0,NOW(),NOW(),'en','Presentation file'),
('conference_ckeywords',1,NOW(),NOW(),'en','Keywords:'),
('conference_ckeywords',1,NOW(),NOW(),'bg','РљР»СЋС‡РѕРІРё РґСѓРјРё:'),
('conference_cnnotedit',1,NOW(),NOW(),'bg','Р’РёРµ РЅРµ РјРѕР¶Рµ РґР° СЂРµРґР°РєС‚РёСЂР°С‚Рµ С‚РѕР·Рё РґРѕРєР»Р°Рґ.'),
('conference_cnnotedit',1,NOW(),NOW(),'en','You have no permission to edit this data.'),
('conference_confirmdel',0,NOW(),NOW(),'bg','РќР°РёСЃС‚РёРЅР° Р»Рё РёСЃРєР°С‚Рµ РґР° РёР·С‚СЂРёРµС‚Рµ С‚РѕР·Рё РґРѕРєР»Р°Рґ? РўРѕРІР° С‰Рµ РёР·С‚СЂРёРµ РІСЃРёС‡РєРё РґР°РЅРЅРё Рё РєР°С‡РµРЅРё С„Р°Р№Р»РѕРІРµ Р·Р° РґРѕРєР»Р°РґР° Рё РЅСЏРјР° РґР° РјРѕР¶Рµ РїРѕРІРµС‡Рµ РґР° СЃРµ РІСЉР·СЃС‚Р°РЅРѕРІСЏС‚.'),
('conference_confirmdel',0,NOW(),NOW(),'en','Are you sure you want to delete this report? This will delete all the data and uploaded files for the report and will no longer be able to recover.'),
('conference_confirmdeluser',0,NOW(),NOW(),'bg','РќР°РёСЃС‚РёРЅР° Р»Рё РёСЃРєР°С‚Рµ РґР° РёР·С‚СЂРёРµС‚Рµ СЃРІРѕСЏ РїСЂРѕС„РёР»? РўРѕРІР° С‰Рµ РёР·С‚СЂРёРµ РІСЃРёС‡РєРё Р’Р°С€Рё РґР°РЅРЅРё РѕС‚ СЃР°Р№С‚Р° Р±РµР· РІСЉР·РјРѕР¶РЅРѕСЃС‚ РґР° РіРё РІСЉР·СЃС‚Р°РЅРѕРІРёС‚Рµ.'),
('conference_confirmdeluser',0,NOW(),NOW(),'en','Are you sure you want to delete your account? This will delete all of your site data without the ability to restore them.'),
('conference_csubmit',1,NOW(),NOW(),'en','Save data'),
('conference_csubmit',1,NOW(),NOW(),'bg','Р—Р°РїР°Р·РІР°РЅРµ РЅР° РґР°РЅРЅРёС‚Рµ'),
('conference_ctitle',1,NOW(),NOW(),'en','Title:'),
('conference_ctitle',1,NOW(),NOW(),'bg','Р—Р°РіР»Р°РІРёРµ:'),
('conference_ctopic',1,NOW(),NOW(),'en','Conference topic:'),
('conference_ctopic',1,NOW(),NOW(),'bg','РўРµРјР°С‚РёС‡РЅРѕ РЅР°РїСЂР°РІР»РµРЅРёРµ:'),
('conference_deletepaper',0,NOW(),NOW(),'bg','РР·С‚СЂРёРІР°РЅРµ РЅР° РґРѕРєР»Р°РґР°'),
('conference_deletepaper',1,NOW(),NOW(),'en','Delete report'),
('conference_deleteuser',0,NOW(),NOW(),'bg','РР·С‚СЂРёРІР°РЅРµ РЅР° РїСЂРѕС„РёР»Р°'),
('conference_deleteuser',0,NOW(),NOW(),'en','Delete account'),
('conference_dfull',0,NOW(),NOW(),'en','Full Text Download'),
('conference_dfull',0,NOW(),NOW(),'bg','РџСЉР»РµРЅ С‚РµРєСЃС‚'),
('conference_editpaper',1,NOW(),NOW(),'en','Edit data'),
('conference_editpaper',1,NOW(),NOW(),'bg','Р РµРґР°РєС‚РёСЂР°РЅРµ'),
('conference_emcofirmed',1,NOW(),NOW(),'bg','Р’Р°С€РёСЏС‚ РёРјРµР№Р» Р°РґСЂРµСЃ Рµ РїРѕС‚РІСЉСЂРґРµРЅ. Р—Р° РІСЃРёР·Р°РЅРµ РІ СЃР°Р№С‚Р° РёР·РїРѕР»Р·РІР°Р№С‚Рµ РєР°С‚Рѕ РїРѕС‚СЂРµР±РёС‚РµР»СЃРєРѕ РёРјРµ СЃРІРѕСЏ РёРјРµР№Р» Р°РґСЂРµСЃ Рё РїР°СЂРѕР»Р°С‚Р°, РєРѕСЏС‚Рѕ Р·Р°РґР°РґРѕС…С‚Рµ РїСЂРё СЂРµРіРёСЃС‚СЂР°С†РёСЏС‚Р°.'),
('conference_emcofirmed',1,NOW(),NOW(),'en','Your email address is confirmed. To log in the site, use your email address as username and the password you set during the registration.'),
('conference_fee',1,NOW(),NOW(),'bg','РџР»Р°С‚РµРЅР° С‚Р°РєСЃР°<sup>1</sup>:'),
('conference_fee',1,NOW(),NOW(),'en','Fee paid<sup>1</sup>:'),
('conference_feenote',1,NOW(),NOW(),'bg','<p><sup>1</sup> РЎСѓРјР°С‚Р° РЅР° РїР»Р°С‚РµРЅР°С‚Р° С‚Р°РєСЃР° С‰Рµ СЃРµ РїРѕРєР°Р¶Рµ С‚СѓРє СЃР»РµРґ РїРѕС‚РІСЉСЂР¶РґРµРЅРёРµ РѕС‚ Р¤РёРЅР°РЅСЃРѕРІРѕ-СЃС‡РµС‚РѕРІРѕРґРµРЅ РѕС‚РґРµР».</p>'),
('conference_feenote',1,NOW(),NOW(),'en','<p><sup>1</sup> The amount of the fee will appear here after confirmation of Financial Department.</p>'),
('conference_fileagain',1,NOW(),NOW(),'bg','РќР° СЃСЉСЂРІСЉСЂР° РІРµС‡Рµ РёРјР° С„Р°Р№Р» СЃСЉСЃ СЃСЉС‰РѕС‚Рѕ РёРјРµ, РєР°С‡РµРЅ РѕС‚ РґСЂСѓРі СѓС‡Р°СЃС‚РЅРёРє. РњРѕР»СЏ, РїСЂРµРёРјРµРЅСѓРІР°Р№С‚Рµ СЃРІРѕСЏ С„Р°Р№Р» Рё РѕС‚РЅРѕРІРѕ РѕРїРёС‚Р°Р№С‚Рµ РґР° РіРѕ РєР°С‡РёС‚Рµ.'),
('conference_fileagain',1,NOW(),NOW(),'en','There is a file with the same name on the server, may be posted by another participant. Please rename your file and then try to upload it again.'),
('conference_filenotexists',1,NOW(),NOW(),'bg','Р¤Р°Р№Р»СЉС‚ РЅРµ СЃСЉС‰РµСЃС‚РІСѓРІР°! РњРѕР»СЏ, РєР°С‡РµС‚Рµ РіРѕ РѕС‚РЅРѕРІРѕ.'),
('conference_filenotexists',1,NOW(),NOW(),'en','File do not exist! Please, try to upload again.'),
('conference_forms',1,NOW(),NOW(),'bg','$fs = array( \'РџСЂРµР·РµРЅС‚Р°С†РёСЏ\', \'РџРѕСЃС‚РµСЂ\', \'Р¤РёСЂРјРµРЅ РґРѕРєР»Р°Рґ\', \'Р—Р°РґРѕС‡РЅРѕ СѓС‡Р°СЃС‚РёРµ\', \'РЎР»СѓС€Р°С‚РµР»\');\r\n'),
('conference_forms',1,NOW(),NOW(),'en','$fs = array( \'Oral presentation\', \'Poster\', \'Corporative presentation\', \'Part time\', \'Listener\' );'),
('conference_invalidcode',1,NOW(),NOW(),'bg','РќРµРІР°Р»РёРґРµРЅ РєРѕРґ Р·Р° РїРѕС‚РІСЉСЂР¶РґР°РІР°РЅРµ РЅР° СЂРµРіРёСЃС‚СЂР°С†РёСЏ.'),
('conference_invalidcode',1,NOW(),NOW(),'en','Invalid confirmation code.'),
('conference_manyreps',0,NOW(),NOW(),'bg','РРјР° РґР°РЅРЅРё Р·Р° РїРѕРІРµС‡Рµ РѕС‚ РїРѕР·РІРѕР»РµРЅРёСЏ Р±СЂРѕР№ РґРѕРєР»Р°РґРё. Р—Р° РґРѕРєР»Р°РґРёС‚Рµ РЅР°Рґ РґРѕРїСѓСЃС‚РёРјРёСЏ Р±СЂРѕР№, С‚СЂСЏР±РІР° РґР° РїР»Р°С‚РёС‚Рµ РґРѕРїСЉР»РЅРёС‚РµР»РЅР° С‚Р°РєСЃР°, Р·Р° РґР° Р±СЉРґР°С‚ СЂРµС†РµРЅР·РёСЂР°РЅРё Рё РїСѓР±Р»РёРєСѓРІР°РЅРё.'),
('conference_manyreps',0,NOW(),NOW(),'en','There is more than the number of reports allowed. For reports above the allowable number, you must pay an additional fee to be reviewed and published.'),
('conference_Missing',0,NOW(),NOW(),'en','Missing: '),
('conference_Missing',0,NOW(),NOW(),'bg','Р›РёРїСЃРІР°С‚: '),
('conference_mydata',1,NOW(),NOW(),'bg','Р”Р°РЅРЅРё РІ РјРѕСЏ РїСЂРѕС„РёР»:'),
('conference_mydata',1,NOW(),NOW(),'en','My personal data:'),
('conference_mypaper',1,NOW(),NOW(),'en','My participation'),
('conference_mypaper',1,NOW(),NOW(),'bg','РњРѕРµС‚Рѕ СѓС‡Р°СЃС‚РёРµ РІ РєРѕРЅС„РµСЂРµРЅС†РёСЏС‚Р°'),
('conference_mypersonal',1,NOW(),NOW(),'bg','Р РµРґР°РєС‚РёСЂР°РЅРµ РЅР° РїСЂРѕС„РёР»Р°'),
('conference_mypersonal',1,NOW(),NOW(),'en','Edit my personal data'),
('conference_noabs',1,NOW(),NOW(),'bg','РЎСЂРѕРєСЉС‚ Р·Р° РёР·РїСЂР°С‰Р°РЅРµ РЅР° СЂРµР·СЋРјРµС‚Р° Рµ РёР·С‚РµРєСЉР». РЎРµРіР° РјРѕР¶Рµ РґР° РєР°С‡РёС‚Рµ СЃР°РјРѕ С„Р°Р№Р»РѕРІРµ СЃ РїСЉР»РЅРёСЏ С‚РµРєСЃС‚ РЅР° РґРѕРєР»Р°РґРё.'),
('conference_noabs',1,NOW(),NOW(),'en','The deadline for abstracts has passed. Now you can upload only files with the full report.'),
('conference_noabs1',1,NOW(),NOW(),'bg','РќСЏРјР° РґР°РЅРЅРё Р·Р° РґРѕРєР»Р°РґРё'),
('conference_noabs1',1,NOW(),NOW(),'en','You have no reports yet.'),
('conference_noAbstract',0,NOW(),NOW(),'bg','СЂРµР·СЋРјРµ, '),
('conference_noAprAbstract',0,NOW(),NOW(),'bg','РѕРґРѕР±СЂРµРЅРѕ СЂРµР·СЋРјРµ, '),
('conference_noAprAbstract',0,NOW(),NOW(),'en','approved abstract, '),
('conference_noDoc',0,NOW(),NOW(),'bg','DOC С„Р°Р№Р», '),
('conference_noDoc',0,NOW(),NOW(),'en','DOC file, '),
('conference_noFee',0,NOW(),NOW(),'bg','С‚Р°РєСЃР°, '),
('conference_noFee',0,NOW(),NOW(),'en','fee, '),
('conference_nofull',1,NOW(),NOW(),'bg','РЎСЂРѕРєСЉС‚ Р·Р° СЂРµРіРёСЃС‚СЂРёСЂР°РЅРµ РЅР° РґРѕРєР»Р°РґРё Рµ РёР·С‚РµРєСЉР».'),
('conference_nofull',1,NOW(),NOW(),'en','The deadline for registration of reports is expired. '),
('conference_noKeyWords',0,NOW(),NOW(),'bg','РєР»СЋС‡РѕРІРё РґСѓРјРё, '),
('conference_noKeyWords',0,NOW(),NOW(),'en','key words, '),
('conference_noPDF',0,NOW(),NOW(),'bg','PDF С„Р°Р№Р», '),
('conference_noPDF',0,NOW(),NOW(),'en','PDF file, '),
('conference_notspec',1,NOW(),NOW(),'bg','РќРµ СЃР° РїРѕСЃРѕС‡РёР»Рё'),
('conference_notspec',1,NOW(),NOW(),'en','Not specified'),
('conference_noupload',1,NOW(),NOW(),'bg','Р—Р° СЃСЉР¶Р°Р»РµРЅРёРµ, С„Р°Р№Р»СЉС‚ РЅРµ СЃРµ РєР°С‡Рё СѓСЃРїРµС€РЅРѕ. РњРѕР»СЏ, РёР·РїСЂР°С‚РµС‚Рµ РіРѕ РЅР° РёРјРµР№Р» <a href="mailto:conference_bg@vsu.bg">conference_bg@vsu.bg</a>.'),
('conference_noupload',1,NOW(),NOW(),'en','Unfortunately, the file is not uploaded successfully. Please send it to email <a href="mailto:conference_bg@vsu.bg">conference_en@vsu.bg</a>.'),
('conference_partcount',1,NOW(),NOW(),'bg','Р‘СЂРѕР№ РѕРЅР»Р°Р№РЅ СЂРµРіРёСЃС‚СЂР°С†РёРё'),
('conference_partcount',1,NOW(),NOW(),'en','Number of online registrations'),
('conference_pg',0,NOW(),NOW(),'bg','СЃС‚СЂ. '),
('conference_pg',0,NOW(),NOW(),'en','p. '),
('conference_posters',0,NOW(),NOW(),'bg','РџРѕСЃС‚РµСЂРё'),
('conference_posters',0,NOW(),NOW(),'en','Posters'),
('conference_pregsubmit',1,NOW(),NOW(),'en','Registration'),
('conference_pregsubmit',1,NOW(),NOW(),'bg','Р РµРіРёСЃС‚СЂРёСЂР°РЅРµ'),
('conference_prez',0,NOW(),NOW(),'bg','РџСЂРµР·РµРЅС‚Р°С†РёСЏ'),
('conference_prez',0,NOW(),NOW(),'en','Presentation Download'),
('conference_proccount',1,NOW(),NOW(),'bg','Р‘СЂРѕР№ РёР·РїСЂР°С‚РµРЅРё СЂРµР·СЋРјРµС‚Р°'),
('conference_proccount',1,NOW(),NOW(),'en','Number of abstracts sent'),
('conference_recaptcha',1,NOW(),NOW(),'bg','РљРѕРґ Р·Р° СЃРёРіСѓСЂРЅРѕСЃС‚<br>\r\nReCaptcha'),
('conference_recaptcha',1,NOW(),NOW(),'en','Security Code:<br>\r\n(ReCaptcha)'),
('conference_regcmess',1,NOW(),NOW(),'bg','Р—РґСЂР°РІРµР№С‚Рµ,\r\n\r\nР’Р°С€РёСЏС‚ РёРјРµР№Р» Р°РґСЂРµСЃ Рµ РёР·РїРѕР»Р·РІР°РЅ Р·Р° СЂРµРіРёСЃС‚СЂРёСЂР°РЅРµ РЅР° РїРѕС‚СЂРµР±РёС‚РµР» РёР»Рё СЃРјСЏРЅР° РЅР° РїР°СЂРѕР»Р°С‚Р° РЅР° СЂРµРіРёСЃС‚СЂРёСЂР°РЅ РїРѕС‚СЂРµР±РёС‚РµР» РЅР° СЃР°Р№С‚Р° http://www.vsu.bg\r\n\r\nРђРєРѕ С‚РѕРІР° РЅРµ СЃС‚Рµ РЅР°РїСЂР°РІРёР»Рё Р’РёРµ, РјРѕР»СЏ, РЅРµ РїСЂР°РІРµС‚Рµ РЅРёС‰Рѕ,\r\n\r\nРЅРѕ Р°РєРѕ РЅР°РёСЃС‚РёРЅР° РёСЃРєР°С‚Рµ РґР° РїРѕС‚РІСЉСЂРґРёС‚Рµ СЂРµРіРёСЃС‚СЂР°С†РёСЏС‚Р° (СЃРјСЏРЅР°С‚Р° РЅР° РїР°СЂРѕР»Р°С‚Р°) СЃРё, РѕС‚РІРѕСЂРµС‚Рµ РІ Р±СЂР°СѓР·СЉСЂР° СЃРё СЃР»РµРґРЅРёСЏ Р°РґСЂРµСЃ:\r\n\r\n'),
('conference_regcmess',1,NOW(),NOW(),'en','Hello,\r\n\r\nYour email address is used to register a new user or to change the password of a registered user of the site http://www.vsu.bg\r\n\r\nIf you did not make this, please do not do anything,\r\n\r\nbut if you really want to confirm your registration (password change), open in your browser this URL:\r\n\r\n'),
('conference_shoeafter',0,NOW(),NOW(),'en','This information will be published after'),
('conference_shoeafter',0,NOW(),NOW(),'bg','РўР°Р·Рё РёРЅС„РѕСЂРјР°С†РёСЏ С‰Рµ Р±СЉРґРµ РїСѓР±Р»РёРєСѓРІР°РЅР° СЃР»РµРґ'),
('conference_title',1,NOW(),NOW(),'bg','РњРµР¶РґСѓРЅР°СЂРѕРґРЅР° РЅР°СѓС‡РЅР° РєРѕРЅС„РµСЂРµРЅС†РёСЏ VSU\''),
('conference_title',1,NOW(),NOW(),'en','International Scientific Conference VSU\''),
('conference_topics',1,NOW(),NOW(),'en','$tp = array(\r\n\'Topic 1\',\r\n\'Topic 2\',\r\n\'Topic 3\',\r\n\'Topic 4\'\r\n);'),
('conference_topics',1,NOW(),NOW(),'bg','$tp = array(\r\n\'РќР°РїСЂР°РІР»РµРЅРёРµ 1\',\r\n\'РќР°РїСЂР°РІР»РµРЅРёРµ 2\',\r\n\'РќР°РїСЂР°РІР»РµРЅРёРµ 3\',\r\n\'РќР°РїСЂР°РІР»РµРЅРёРµ 4\',\r\n\'РќР°РїСЂР°РІР»РµРЅРёРµ 5\'\r\n);');