INSERT INTO `content` (`name`,`nolink`,`date_time_1`,`date_time_2`,`language`,`text`) VALUES
('conference_1paper',1,NOW(),NOW(),'en','First report:'),
('conference_1paper',1,NOW(),NOW(),'bg','Първи доклад:'),
('conference_2paper',1,NOW(),NOW(),'en','Second report:'),
('conference_2paper',1,NOW(),NOW(),'bg','Втори доклад:'),
('conference_by',1,NOW(),NOW(),'bg','Заявен от:'),
('conference_by',1,NOW(),NOW(),'en','Sent by:'),
('conference_bycat',1,NOW(),NOW(),'bg','Брой резюмета по тематични направления'),
('conference_bycat',1,NOW(),NOW(),'en','Number of abstracts by topic'),
('conference_bycountry',1,NOW(),NOW(),'bg','По държави'),
('conference_bycountry',1,NOW(),NOW(),'en','By countries'),
('conference_byform',1,NOW(),NOW(),'bg','По форма на представяне'),
('conference_byform',1,NOW(),NOW(),'en','By registration form'),
('conference_cabstract',1,NOW(),NOW(),'en','Abstract:'),
('conference_cabstract',1,NOW(),NOW(),'bg','Резюме:'),
('conference_caddresses',1,NOW(),NOW(),'en','Addresses of authors:'),
('conference_caddresses',1,NOW(),NOW(),'bg','Адрес/адреси на авторите:'),
('conference_cauthors',1,NOW(),NOW(),'en','Authors:'),
('conference_cauthors',1,NOW(),NOW(),'bg','Автори:'),
('conference_cdate1',1,NOW(),NOW(),'en','First registered:'),
('conference_cdate1',1,NOW(),NOW(),'bg','Първо регистриране:'),
('conference_cdate2',1,NOW(),NOW(),'en','Last edited:'),
('conference_cdate2',1,NOW(),NOW(),'bg','Последна редакция:'),
('conference_cemail',1,NOW(),NOW(),'bg','Моля проверете си имейла и отворете адреса, който Ви беше изпратен.'),
('conference_cemail',1,NOW(),NOW(),'en','Please check your email and open the web address that was sent.'),
('conference_cfile',1,NOW(),NOW(),'en','File with the full text:'),
('conference_cfile',1,NOW(),NOW(),'bg','Файл с пълния текст:'),
('conference_cform',1,NOW(),NOW(),'bg','Форма на представяне:'),
('conference_cform',1,NOW(),NOW(),'en','Form of presentation:'),
('conference_cfulltextfile',1,NOW(),NOW(),'en','DOC file with the full text:'),
('conference_cfulltextfile',1,NOW(),NOW(),'bg','DOC файл с пълния текст:'),
('conference_cfulltextfile2',1,NOW(),NOW(),'en','PDF file with the full text:'),
('conference_cfulltextfile2',1,NOW(),NOW(),'bg','PDF файл с пълния текст:'),
('conference_cfulltextfile3',0,NOW(),NOW(),'bg','Презентация за пленарен доклад'),
('conference_cfulltextfile3',0,NOW(),NOW(),'en','Presentation file'),
('conference_ckeywords',1,NOW(),NOW(),'en','Keywords:'),
('conference_ckeywords',1,NOW(),NOW(),'bg','Ключови думи:'),
('conference_cnnotedit',1,NOW(),NOW(),'bg','Вие не може да редактирате този доклад.'),
('conference_cnnotedit',1,NOW(),NOW(),'en','You have no permission to edit this data.'),
('conference_csubmit',1,NOW(),NOW(),'en','Save data'),
('conference_csubmit',1,NOW(),NOW(),'bg','Запазване на данните'),
('conference_ctitle',1,NOW(),NOW(),'en','Title:'),
('conference_ctitle',1,NOW(),NOW(),'bg','Заглавие:'),
('conference_ctopic',1,NOW(),NOW(),'en','Conference topic:'),
('conference_ctopic',1,NOW(),NOW(),'bg','Тематично направление:'),
('conference_dfull',0,NOW(),NOW(),'en','Full Text Download'),
('conference_dfull',0,NOW(),NOW(),'bg','Пълен текст'),
('conference_editpaper',1,NOW(),NOW(),'en','Edit data'),
('conference_editpaper',1,NOW(),NOW(),'bg','Редактиране'),
('conference_emcofirmed',1,NOW(),NOW(),'bg','Вашият имейл адрес е потвърден. За всизане в сайта използвайте като потребителско име своя имейл адрес и паролата, която зададохте при регистрацията.'),
('conference_emcofirmed',1,NOW(),NOW(),'en','Your email address is confirmed. To log in the site, use your email address as username and the password you set during the registration.'),
('conference_fee',1,NOW(),NOW(),'bg','Платена такса<sup>1</sup>:'),
('conference_fee',1,NOW(),NOW(),'en','Fee paid<sup>1</sup>:'),
('conference_feenote',1,NOW(),NOW(),'bg','<p><sup>1</sup> Сумата на платената такса ще се покаже тук след потвърждение от Финансово-счетоводен отдел.</p>'),
('conference_feenote',1,NOW(),NOW(),'en','<p><sup>1</sup> The amount of the fee will appear here after confirmation of Financial Department.</p>'),
('conference_fileagain',1,NOW(),NOW(),'bg','На сървъра вече има файл със същото име, качен от друг участник. Моля, преименувайте своя файл и отново опитайте да го качите.'),
('conference_fileagain',1,NOW(),NOW(),'en','There is a file with the same name on the server, may be posted by another participant. Please rename your file and then try to upload it again.'),
('conference_filenotexists',1,NOW(),NOW(),'bg','Файлът не съществува! Моля, качете го отново.'),
('conference_filenotexists',1,NOW(),NOW(),'en','File do not exist! Please, try to upload again.'),
('conference_forms',1,NOW(),NOW(),'bg','$fs = array( \'Презентация\', \'Постер\', \'Фирмен доклад\', \'Задочно участие\', \'Слушател\');\r\n'),
('conference_forms',1,NOW(),NOW(),'en','$fs = array( \'Oral presentation\', \'Poster\', \'Corporative presentation\', \'Part time\', \'Listener\' );'),
('conference_invalidcode',1,NOW(),NOW(),'bg','Невалиден код за потвърждаване на регистрация.'),
('conference_invalidcode',1,NOW(),NOW(),'en','Invalid confirmation code.'),
('conference_mydata',1,NOW(),NOW(),'bg','Данни в моя профил:'),
('conference_mydata',1,NOW(),NOW(),'en','My personal data:'),
('conference_mypaper',1,NOW(),NOW(),'en','My participation'),
('conference_mypaper',1,NOW(),NOW(),'bg','Моето участие в конференцията'),
('conference_mypersonal',1,NOW(),NOW(),'bg','Редактиране на профила'),
('conference_mypersonal',1,NOW(),NOW(),'en','Edit my personal data'),
('conference_noabs',1,NOW(),NOW(),'bg','Срокът за изпращане на резюмета е изтекъл. Сега може да качите само файлове с пълния текст на доклади.'),
('conference_noabs',1,NOW(),NOW(),'en','The deadline for abstracts has passed. Now you can upload only files with the full report.'),
('conference_noabs1',1,NOW(),NOW(),'bg','Няма данни за доклади'),
('conference_noabs1',1,NOW(),NOW(),'en','You have no reports yet.'),
('conference_nofull',1,NOW(),NOW(),'bg','Срокът за регистриране на доклади е изтекъл.'),
('conference_nofull',1,NOW(),NOW(),'en','The deadline for registration of reports is expired. '),
('conference_notspec',1,NOW(),NOW(),'bg','Не са посочили'),
('conference_notspec',1,NOW(),NOW(),'en','Not specified'),
('conference_noupload',1,NOW(),NOW(),'bg','За съжаление, файлът не се качи успешно. Моля, изпратете го на имейл <a href="mailto:conference_bg@vsu.bg">conference_bg@vsu.bg</a>.'),
('conference_noupload',1,NOW(),NOW(),'en','Unfortunately, the file is not uploaded successfully. Please send it to email <a href="mailto:conference_bg@vsu.bg">conference_en@vsu.bg</a>.'),
('conference_partcount',1,NOW(),NOW(),'bg','Брой онлайн регистрации'),
('conference_partcount',1,NOW(),NOW(),'en','Number of online registrations'),
('conference_pg',0,NOW(),NOW(),'bg','стр. '),
('conference_pg',0,NOW(),NOW(),'en','p. '),
('conference_posters',0,NOW(),NOW(),'bg','Постери'),
('conference_posters',0,NOW(),NOW(),'en','Posters'),
('conference_pregsubmit',1,NOW(),NOW(),'en','Registration'),
('conference_pregsubmit',1,NOW(),NOW(),'bg','Регистриране'),
('conference_prez',0,NOW(),NOW(),'bg','Презентация'),
('conference_prez',0,NOW(),NOW(),'en','Presentation Download'),
('conference_proccount',1,NOW(),NOW(),'bg','Брой изпратени резюмета'),
('conference_proccount',1,NOW(),NOW(),'en','Number of abstracts sent'),
('conference_recaptcha',1,NOW(),NOW(),'bg','Код за сигурност<br>\r\nReCaptcha'),
('conference_recaptcha',1,NOW(),NOW(),'en','Security Code:<br>\r\n(ReCaptcha)'),
('conference_regcmess',1,NOW(),NOW(),'bg','Здравейте,\r\n\r\nВашият имейл адрес е използван за регистриране на потребител или смяна на паролата на регистриран потребител на сайта http://www.vsu.bg\r\n\r\nАко това не сте направили Вие, моля, не правете нищо,\r\n\r\nно ако наистина искате да потвърдите регистрацията (смяната на паролата) си, отворете в браузъра си следния адрес:\r\n\r\n'),
('conference_regcmess',1,NOW(),NOW(),'en','Hello,\r\n\r\nYour email address is used to register a new user or to change the password of a registered user of the site http://www.vsu.bg\r\n\r\nIf you did not make this, please do not do anything,\r\n\r\nbut if you really want to confirm your registration (password change), open in your browser this URL:\r\n\r\n'),
('conference_title',1,NOW(),NOW(),'bg','Международна научна конференция VSU\''),
('conference_title',1,NOW(),NOW(),'en','International Scientific Conference VSU\''),
('conference_topics',1,NOW(),NOW(),'en','$tp = array(\r\n\'   I. Architecture and Urbanism\',\r\n\'  II. Art and Conservation of Architectural Heritage\',\r\n\' III. Structural Mechanics\',\r\n\'  IV. Building Structures\',\r\n\'   V. Building Physics and Materials Science\',\r\n\'  VI. Technology, Management and Economics of Construction\',\r\n\' VII. Sustainable Development and Environmental Security\',\r\n\'VIII. Student Section\',\r\n\'IX. College student Section\'\r\n);'),
('conference_topics',1,NOW(),NOW(),'bg','$tp = array(\r\n\'   I. Архитектура и урбанизъм\',\r\n\'  II. Изкуство и опазване на архитектурното наследство\',\r\n\' III. Строителна механика\',\r\n\'  IV. Строителни конструкции\',\r\n\'   V. Строителна физика и материалознание\',\r\n\'  VI. Технология и управление на строителството\',\r\n\' VII. Устойчиво строителство и екологична сигурност\',\r\n\'VIII. Студентска секция\',\r\n\' IХ. Ученическа секция\'\r\n);');