INSERT INTO `content` (`name`,`nolink`,`date_time_1`,`date_time_2`,`language`,`text`) VALUES
('cookies_clear',0,NOW(),NOW(),'bg','Изтриване на "Бисквитките"'),
('cookies_clear',0,NOW(),NOW(),'en','Delete all cookies from this site'),
('cookies_cols_description',0,NOW(),NOW(),'bg','"Бисквитка", необходима при администриране на сайта.'),
('cookies_cookies_accept_description',0,NOW(),NOW(),'bg','Вашият отговор дали приемате "бисквитките" от сайта.'),
('cookies_cookies_accept_description',0,NOW(),NOW(),'en','Your answer if you accept cookies from this site.'),
('cookies_description',0,NOW(),NOW(),'bg','Описание'),
('cookies_description',0,NOW(),NOW(),'en','Description'),
('cookies_edit_description',0,NOW(),NOW(),'bg','"Бисквитка", необходима при администриране на сайта.'),
('cookies_fontSize_description',0,NOW(),NOW(),'bg','Размер на шрифта, който сте нагласили'),
('cookies_K6cQ_description',0,NOW(),NOW(),'bg','"Бисквитка", необходима при администриране на сайта.'),
('cookies_K6cQ_description',0,NOW(),NOW(),'en','For administrative purposes'),
('cookies_language_description',0,NOW(),NOW(),'bg','Предпочитания от Вас език.'),
('cookies_language_description',0,NOW(),NOW(),'en','Your preferred language. '),
('cookies_last_a_description',0,NOW(),NOW(),'bg','Означава, че сте отговорили на въпроса дали искате да посетите отново последната страница'),
('cookies_last_pid_description',0,NOW(),NOW(),'bg','Номера на последно посетената от Вас страница'),
('cookies_last_url_description',0,NOW(),NOW(),'bg','Адреса на последната, посетена от Вас страница'),
('cookies_lid_description',0,NOW(),NOW(),'bg','"Бисквитка", необходима при администриране на сайта.'),
('cookies_limit_description',0,NOW(),NOW(),'en','For administrative purposes'),
('cookies_limit_description',0,NOW(),NOW(),'bg','"Бисквитка", необходима при администриране на сайта.'),
('cookies_mark10_description',0,NOW(),NOW(),'bg','"Бисквитка", използвана от модул "Моите страници"'),
('cookies_mark118_description',0,NOW(),NOW(),'bg','Заглавието и адреса на последната страница от сайта, която сте посетили.'),
('cookies_mark25_description',0,NOW(),NOW(),'bg','"Бисквитка", използвана от модул "Моите страници"'),
('cookies_message',0,NOW(),NOW(),'en','<p>This website uses cookies to ensure you get the best experience on our website. <a href="/index.php?pid=108">More info</a>. &nbsp; <a href="" onclick="cookies_accept();">Got It</a>!</p>\r\n'),
('cookies_message',0,NOW(),NOW(),'bg','<p>За да бъде по-удобно и приятно Вашето посещение, този сайт използва &quot;бисквитки&quot;. <a href="/index.php?pid=5">Вижте повече</a>. Съгласни ли сте да приемете тези &quot;бисквитки&quot;?&nbsp; <a href="" onclick="cookies_accept();">ДА</a></p>\r\n'),
('cookies_mj8d_description',0,NOW(),NOW(),'bg','"Бисквитка", необходима при администриране на сайта.'),
('cookies_mj8d_description',0,NOW(),NOW(),'en','For administrative purposes'),
('cookies_name',0,NOW(),NOW(),'bg','Име на "бисквитка"'),
('cookies_name',0,NOW(),NOW(),'en','Cookie name'),
('cookies_noadm_description',0,NOW(),NOW(),'bg','"Бисквитка", необходима при администриране на сайта.'),
('cookies_noadm_description',0,NOW(),NOW(),'en','For administrative purposes'),
('cookies_nocookie',0,NOW(),NOW(),'bg','Вашият браузър не е запазил "бисквитки" от този сайт.'),
('cookies_PHPSESSID_description',0,NOW(),NOW(),'bg','Уникален номер на Вашата сесия.'),
('cookies_PHPSESSID_description',0,NOW(),NOW(),'en','Unique identifier for your session.'),
('cookies_policy',0,NOW(),NOW(),'bg','<p>\r\n	&quot;Бисквитки&quot; (cookies) се наричат малки порции информация, които Вашият браузър запазва във Вашето устроство (компютър) по заявки от посещаваните сайтове. При следващо отваряне на страница запазената информация се изпраща от браузъра към сайта и тя се използва за адаптиране на показваната от сайта информация спрямо предишните Ви действия в сайта.</p>\r\n<p>Всяка "бисквитка" се разпознава по нейното име и служи за съхраняване върху Вашето устройство, в продължение на определено време, на информация под формата на кратък текст, представляващ стойността на "бисквитката". Продължителността на съхранение на всяка "бисквитка" се задава при нейното създаване и може да бъде до момента на затваряне на браузъра или до зададена дата и час. "Бисквитките" от нашия сайт имат продължителност 30 денонощия от момента на създаване.</p>\r\n<p>\r\n	Чрез настройване на браузъра си Вие можете да блокирате запазването на &quot;бисквитки&quot; от нашия сайт, но това би довело до неудобства при използване на сайта.</p>\r\n<p>\r\n	&quot;Бисквитки&quot; са необходими:</p>\r\n<ul>\r\n	<li>\r\n		когато влизате в сайта с потребителско име и парола, за да Ви разпознае сайта по уникалната стойност на запазена за тази цел &quot;бисквитка&quot;;</li>\r\n	<li>\r\n		за да се показват страниците, които отваряте, на вече избрания от Вас език;</li>\r\n	<li>\r\n		при показване на реклами.</li>\r\n</ul>\r\n\r\n'),
('cookies_rows_description',0,NOW(),NOW(),'bg','"Бисквитка", необходима при администриране на сайта.'),
('cookies_smh_description',0,NOW(),NOW(),'bg','Предпочели сте да скриете линковете в горната част на страниците'),
('cookies_table',0,NOW(),NOW(),'bg','"Бисквитките", запазени по заявка от този сайт във Вашето устройство са:'),
('cookies_table',0,NOW(),NOW(),'en','Cookies from this site saved on your device:'),
('cookies_u7zld6_description',0,NOW(),NOW(),'bg','"Бисквитка", необходима при администриране на сайта.'),
('cookies_value',0,NOW(),NOW(),'bg','Стойност'),
('cookies_value',0,NOW(),NOW(),'en','Cookie value'),
('cookies_wup3wg_description',0,NOW(),NOW(),'bg','"Бисквитка", необходима при администриране на сайта.'),
('cookies__gat_description',0,NOW(),NOW(),'bg','"Бисквитка" от Google'),
('cookies__ga_description',0,NOW(),NOW(),'bg','"Бисквитка" от Google'),
('cookies__gid_description',0,NOW(),NOW(),'bg','"Бисквитка" от Google'),
('cookies___utma_description',0,NOW(),NOW(),'bg','"Бисквитка" от Google'),
('cookies___utmc_description',0,NOW(),NOW(),'bg','"Бисквитка" от Google групи'),
('cookies___utmz_description',0,NOW(),NOW(),'bg','"Бисквитка" от Google');