INSERT INTO `content` (`name`,`nolink`,`date_time_1`,`date_time_2`,`language`,`text`) VALUES
('cookies_clear',0,NOW(),NOW(),'bg','Изтриване на "Бисквитките"'),
('cookies_clear',0,NOW(),NOW(),'en','Delete all cookies from this site'),
('cookies_cols_description',0,NOW(),NOW(),'bg','"Бисквитка", необходима при администриране на сайта.'),
('cookies_cookies_accept_description',0,NOW(),NOW(),'bg','Вашият отговор дали приемате \"бисквитките\" от сайта.'),
('cookies_cookies_accept_description',0,NOW(),NOW(),'en','Your answer if you accept cookies from this site.'),
('cookies_description',0,NOW(),NOW(),'bg','Описание'),
('cookies_description',0,NOW(),NOW(),'en','Description'),
('cookies_K6cQ_description',0,NOW(),NOW(),'bg','"Бисквитка", необходима при администриране на сайта.'),
('cookies_K6cQ_description',0,NOW(),NOW(),'en','For administrative purposes'),
('cookies_language_description',0,NOW(),NOW(),'bg','Предпочитания от Вас език.'),
('cookies_language_description',0,NOW(),NOW(),'en','Your preferred language. '),
('cookies_limit_description',0,NOW(),NOW(),'en','For administrative purposes'),
('cookies_limit_description',0,NOW(),NOW(),'bg','"Бисквитка", необходима при администриране на сайта.'),
('cookies_message',0,NOW(),NOW(),'en','<p>This website uses cookies to ensure you get the best experience on our website. <a href="/index.php?pid=108">More info</a>. &nbsp; <a href="" onclick="cookies_accept();">Got It</a>!</p>\r\n'),
('cookies_message',0,NOW(),NOW(),'bg','<p>За да бъде по-удобно и приятно Вашето посещение, този сайт използва &quot;бисквитки&quot;. <a href="/index.php?pid=108">Вижте повече</a>. Съгласни ли сте да приемете тези &quot;бисквитки&quot;?&nbsp; <a href="" onclick="cookies_accept();">ДА</a></p>\r\n'),
('cookies_mj8d_description',0,NOW(),NOW(),'bg','"Бисквитка", необходима при администриране на сайта.'),
('cookies_mj8d_description',0,NOW(),NOW(),'en','For administrative purposes'),
('cookies_name',0,NOW(),NOW(),'bg','Име на "бисквитка"'),
('cookies_name',0,NOW(),NOW(),'en','Cookie name'),
('cookies_noadm_description',0,NOW(),NOW(),'bg','"Бисквитка", необходима при администриране на сайта.'),
('cookies_noadm_description',0,NOW(),NOW(),'en','For administrative purposes'),
('cookies_nocookie',0,NOW(),NOW(),'bg','Вашият браузър не е запазил "бисквитки" от този сайт.'),
('cookies_PHPSESSID_description',0,NOW(),NOW(),'bg','Уникален номер на Вашата сесия.'),
('cookies_PHPSESSID_description',0,NOW(),NOW(),'en','Unique identifier for your session.'),
('cookies_rows_description',0,NOW(),NOW(),'bg','"Бисквитка", необходима при администриране на сайта.'),
('cookies_table',0,NOW(),NOW(),'bg','"Бисквитките", запазени по заявка от този сайт във Вашето устройство са:'),
('cookies_table',0,NOW(),NOW(),'en','Cookies from this site saved on your device:'),
('cookies_value',0,NOW(),NOW(),'bg','Стойност'),
('cookies_value',0,NOW(),NOW(),'en','Cookie value');